project:
  type: website
  output-dir: 'docs'

website:
  title: "Gaussian Mixture Model"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/KEZIAHSALIGUMBA
      - icon: linkedin
        href: https://www.linkedin.com/in/kzsaligumba/
format:
  html:
    theme: cosmo
    css: styles.css
    



